development:
  sessions:
    default:
      # Defines the name of the default database that Mongoid can connect to.
      database: mongoid_sleepingkingstudios_development
      # Provides the hosts the default session can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - localhost:27017
      options:
  # Configure Mongoid specific options. (optional)
  options:
test:
  sessions:
    default:
      database: mongoid_sleepingkingstudios_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
